apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: team-taurus1-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: team-taurus-frontend1-pipeline-run-
      spec:
        serviceAccountName: build-bot-frontend
        pipelineRef:
          name: team-taurus-frontend1-pipeline
        workspaces:
          - name: pipeline-shared-data
            persistentVolumeClaim:
              claimName: team-taurus1-pvc
              # 最終型はfrontendとbackend両方トリガーする
              # https://github.com/tektoncd/triggers/issues/801
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: team-taurus1-backend-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: team-taurus1-backend-pipeline
        workspaces:
          - name: pipeline-shared-data
            persistentVolumeClaim:
              claimName: backend-pvc2
