apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: team-taurus-frontend1-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/tokinori_shimodaira_ibm/team-taurus-frontend1
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-japan-cohort/team-taurus-frontend1.git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: install-dependencies
      runAfter:
        - clone-repository
      taskRef:
        kind: Task
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: ARGS
          value: 
            - clean-install
        - name: PATH_CONTEXT
          value: "webapp"
    # - name: run-tests
    #   runAfter:
    #     - install-dependencies
    #   taskRef:
    #     kind: Task
    #     name: npm
    #   workspaces:
    #     - name: source
    #       workspace: pipeline-shared-data
    #   params:
    #     - name: ARGS
    #       value: 
    #         - test
    #     - name: PATH_CONTEXT
    #       value: "webapp"
    - name: build-image
      runAfter:
        - install-dependencies
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: IMAGE
          #value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
          value: "$(params.image-repo):latest"
        - name: CONTEXT
          value: "webapp"
    - name: kustomize-build-frontend
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: kustomize-build-frontend
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: image-with-tag
          value: "quay.io/tokinori_shimodaira_ibm/team-taurus-frontend1=$(params.image-repo):latest"
    - name: test-deploy-frontend
      runAfter:
        - kustomize-build-frontend
      taskRef:
        kind: Task
        name: test-deploy-frontend
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: app-namespace
          #value: team-gemini
          value: team-taurus1
        - name: app-name
          value: team-taurus-frontend1