apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: team-taurus-frontend1-pipeline-run-
spec:
  serviceAccountName: build-bot-frontend
  pipelineRef:
    name: team-taurus-frontend1-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: team-taurus1-pvc

